name: Cypress Tests

on:
  push:
    branches: [main, develop]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: npm ci

    - name: Run application
      run: npm run dev & npx wait-on http://localhost:5000

    - name: E2E tests
      run: npx cypress run
